#!/bin/bash
. ~/.kodi/addons/plugin.program.basiclauncher/config.cfg
export DISPLAY=:0.0
export PATH=/usr/games:/usr/local/bin:$PATH
export SDL_AUDIODRIVER="alsa"

ratpoison &
RPID=$!
EX=`basename $0`
ARGS=""
for var in "$@"
do
    pattern=" |'"
    if [[ $var =~ $pattern ]]
    then
        ARGS="$ARGS \"$var\""
    else
        ARGS="$ARGS $var"
    fi
done
KPID=`pidof kodi.bin`
EXE=`which $EX`
echo "Executing $EXE $ARGS"
/usr/bin/xdotool mousemove 1920 1080
eval $EXE $ARGS &
/usr/bin/xdotool mousemove 1920 1080
EPID=`pidof $EXE`

echo "Pausing kodi"
kill -SIGSTOP $KPID

echo "Waiting to murder the process $EXE"

/usr/bin/evtest "$device" | while read line; do
  case $line in
    ($event_exit) killall -9 evtest; break ;;
  esac
  echo "$line" >> /tmp/evtest
done

echo "Exiting $EXE"
kill -9 $EPID
kill -SIGCONT $KPID
kill -9 $RPID

